name: Dependency auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # manually trigger a workflow_dispatch event
  workflow_dispatch:

permissions: write-all

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Update Cargo.lock
        run: |
          cargo generate-lockfile || true
          cargo update

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/cargo-deps-update
          title: "chore: cargo update dependencies"
          body: "Automated dependency update via `cargo update`."
          commit-message: "chore: cargo update dependencies"
          add-paths: |
            Cargo.lock
          delete-branch: true

      - name: Auto Merge Pull Request
        continue-on-error: true
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --merge chore/cargo-deps-update
